In [1]:
import numpy as np
from math import sqrt, exp
from scipy.stats import multivariate_normal as mvNormal
import sys

In [2]:
X = np.genfromtxt('X.csv', delimiter=",")
X.shape

(3125, 10)

In [3]:
K = 5
n = X.shape[0]
u = np.random.randint(0, high = n, size =K)
C = X[u]
distances2 = np.zeros((n,K))

In [4]:
#update c
for i in range(K):
    distances2[:,i] = np.sum((X-C[i])**2,axis=1)
clusters = np.argmin(distances2,axis = 1)

In [5]:
#update mu
for i in range(K):
    data = X[clusters == i]
    C[i] = np.average(data,axis=0)

In [6]:
u = np.random.randint(0, high = n, size =K)
C = X[u]
C.shape

(5, 10)

In [7]:
p = np.ones(K) / K
p

array([ 0.2,  0.2,  0.2,  0.2,  0.2])

In [8]:
sigma = np.empty((K,X.shape[1],X.shape[1]))


In [61]:
phi = np.empty((n,K))
sigma = np.repeat(np.identity(X.shape[1])[np.newaxis,...],K,axis=0)
sigma

array([[[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]],

       [[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,

In [10]:
#E step

for i in range(K):
    phi[:,i] = mvNormal.pdf(X,mean = C[i], cov=sigma[i])
phi = phi / np.sum(phi,axis =1).reshape(-1,1)
phi = phi*p
phi.shape

(3125, 5)

In [75]:
#M step
nk = np.sum(phi,axis=0)
p = nk / n
for i in range(K):
    C[i] = np.sum(X * phi[:,i, None],axis=0) / nk[i]
    diff = X-C[i]
    sigma[i] = np.sum( (diff[...,np.newaxis] * diff[:,np.newaxis]) * phi[:,i,None,None],axis = 0)  / nk[i]

(5, 10, 10)

In [70]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [71]:
#A[...,None]*B[:,None]
b = a[...,np.newaxis]
c = a[:,np.newaxis]
print(b.shape)
print(c.shape)
(b*c).shape

(3, 2, 1)
(3, 1, 2)


(3, 2, 2)

In [65]:
np.outer(b,a)

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [14]:
a = np.array([[4.0, 2,],[5,6],
       [2, 3]])
b = np.array([1,3,6])
print(a,b)

(array([[ 4.,  2.],
       [ 5.,  6.],
       [ 2.,  3.]]), array([1, 3, 6]))


array([[ 16.,   8.,  20.,  24.,   8.,  12.],
       [  8.,   4.,  10.,  12.,   4.,   6.],
       [ 20.,  10.,  25.,  30.,  10.,  15.],
       [ 24.,  12.,  30.,  36.,  12.,  18.],
       [  8.,   4.,  10.,  12.,   4.,   6.],
       [ 12.,   6.,  15.,  18.,   6.,   9.]])

In [158]:
np.linalg.norm(a-b,axis=1)

array([ 5.91607978,  7.81024968,  1.        ])